import { Inter } from '@next/font/google';
import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import { AiFillGithub, AiFillLinkedin } from 'react-icons/ai';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import memoji from '../public/AvatarMemoji2.png';

import burger from '../public/icons/burger.webp';
import java from '../public/icons/java.jpg';
import js from '../public/icons/js.jpg';
import node from '../public/icons/node.jpg';
import python from '../public/icons/python.webp';
import react from '../public/icons/react.png';
import sql from '../public/icons/sql.png';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
    const [darkMode, setDarkMode] = useState(false);
    const hoverScale105 = 'transition ease-in-out delay-100 duration-100 hover:scale-105';
    return (
        <div className={darkMode ? 'dark' : ''}>
            <Head>
                <title>Milosz Turczak Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="bg-white px-10 md-px-20 lg:px-40 dark:bg-gray-900 ">
                <section className=" min-h-screen">
                    <nav className=" py-10 mb-12 flex justify-between dark:invert">
                        <h1 className=" text-xl font-burtons">mturczak</h1>
                        <ul className="flex items-center">
                            <li>
                                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className=" cursor-pointer text-xl" />
                            </li>
                            <li>
                                <a className="bg-gradient-to-l from-cyan-500 to-teal-400 text-white px-4 py-2 rounded-md ml-8 dark:invert" href="#">
                                    Resume
                                </a>
                            </li>
                        </ul>
                    </nav>
                    <div className="text-center p-10 py-10 dark:invert ">
                        <h2 className="text-5xl py-2 text-teal-500 font-medium md:text-6xl dark:invert">Milosz Turczak</h2>
                        <h3 className="text-2xl py-2 md:text-3xl">Developer</h3>
                        <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto">Bachelor of Engineering in Computer Science with a specialization in Database Engineering</p>
                    </div>
                    <div className=" text-6xl flex justify-center gap-20 text-gray-700  ">
                        <a href="https://github.com/mturczak">
                            <AiFillGithub className=" cursor-pointer hover:text-gray-500 hover:scale-105 shadow-md rounded-full" />
                        </a>
                        <a href="https://www.linkedin.com/in/milosz-turczak-27a8a0184/">
                            <AiFillLinkedin className=" cursor-pointer hover:text-blue-600 hover:scale-105 shadow-md  " />
                        </a>
                    </div>
                    <div className="relative mx-auto pb-5 bg-gradient-to-t from-blue-200 to-teal-700 rounded-full w-80 h-80 mt-20 mb-20 overflow-hidden  shadow-2xl md:w-96 md:h-96 ">
                        <Image className=" w-70 h-96 " src={memoji} style={{ objectFit: 'cover' }} />+
                    </div>
                </section>
                <section>
                    <div className="dark:invert">
                        <h3 className="text-3xl py-1">Profile</h3>
                        <p className="text-md py-3 leading-8 text-gray-800">
                            I am a Bachelor of Engineering in <span className=" text-blue-500 font-medium dark:invert"> Computer Science </span> with a specialization in{' '}
                            <span className=" text-blue-600 font-medium dark:invert">Database Engineering </span>. I am ambitious and open to new experiences, which causes me to want to take my first
                            steps in the field of IT, so I am looking for my first job as a, generally speaking, software developer where I can use the skills I have learned so far and gain important
                            experience.
                        </p>
                    </div>
                    <div className="dark:invert">
                        <h3 className="text-3xl text-center py-5 mt-3">Projects</h3>
                    </div>
                    <div className={`lg:flex ${hoverScale105} dark:invert `}>
                        <div className="text-center shadow-lg p-10 rounded-xl my-10">
                            <div className=" gap-5 pb-5">
                                <Image className="dark:invert overflow-hidden m-auto" src={burger} width={120} height={120} />
                                <h3 className=" text-2xl font-medium  pt-8 pb-2 "> Aplication supporting the management of the restaurant</h3>
                            </div>

                            <p>
                                This project is my Engineers Thesis about the table reservation system in a particular restaurant. This project will cover the whole range of requirements, that web
                                applications should have. The main features of this application will be: booking tables, adding and deleting, bookings from the owners perspective, and creating a
                                clients account.
                            </p>
                            <a href="https://github.com/mturczak/inzapp">
                                <p className={`py-1 mt-2 shadow-sm font-semibold rounded-lg bg-slate-100 w-32 m-auto ${hoverScale105} hover:text-teal-500 `}>Projects Github</p>
                            </a>
                            <h4 className="py-3 text-teal-500 font-semibold text-lg">Technologies used</h4>
                            <p className="text-gray-800 py-1">React.js</p>
                            <p className="text-gray-800 py-1">Node.js</p>
                            <p className="text-gray-800 py-1">MySQL</p>
                            <p className="text-gray-800 py-1">JSON Web Token</p>
                        </div>
                    </div>
                </section>
                <section>
                    <div className="dark:invert">
                        <h3 className="text-3xl py-1 text-center">Skills and Technologies</h3>
                        <p className="text-center font-light text-sm md:text-xl">( level )</p>
                    </div>

                    <div className="flex flex-row gap-3 py-5  flex-wrap justify-center ">
                        <div className=" basis-[15%] ">
                            <Image src={js} className="rounded-lg object-cover transition ease-in-out delay-100 duration-100 hover:scale-105" width={'100%'} height={'100%'} />
                            <p className="text-center font-light text-sm md:text-xl dark:invert"> bases</p>
                        </div>
                        <div className=" basis-[15%] ">
                            <Image src={react} className="rounded-lg object-cover transition ease-in-out delay-100 duration-100 hover:scale-105" width={'100%'} height={'100%'} />
                            <p className="text-center font-light text-sm md:text-xl dark:invert"> bases</p>
                        </div>
                        <div className=" basis-[15%] ">
                            <Image src={node} className="rounded-lg object-cover transition ease-in-out delay-100 duration-50 hover:scale-105" width={'100%'} height={'100%'} />
                            <p className="text-center font-light text-sm md:text-xl dark:invert"> bases</p>
                        </div>
                        <div className=" basis-[15%] ">
                            <Image src={java} className="rounded-lg object-cover transition ease-in-out delay-100 duration-100 hover:scale-105" width={'100%'} height={'100%'} />
                            <p className="text-center font-light text-sm md:text-xl dark:invert"> bases</p>
                        </div>
                        <div className=" basis-[15%] ">
                            <Image src={python} className="rounded-lg object-cover transition ease-in-out delay-100 duration-100 hover:scale-105" width={'100%'} height={'100%'} />
                            <p className="text-center font-light text-sm md:text-xl dark:invert"> bases</p>
                        </div>
                        <div className=" basis-[15%] ">
                            <Image src={sql} className="rounded-lg object-cover transition ease-in-out delay-100 duration-100 hover:scale-105" width={'100%'} height={'100%'} />
                            <p className="text-center font-light text-sm md:text-xl dark:invert"> bases</p>
                        </div>
                    </div>
                </section>
                <section className="dark:invert">
                    <div>
                        <h3 className="text-3xl py-1 text-center">Education</h3>
                    </div>
                    <div className=" flex place-content-evenly my-10 ">
                        <div className={`shadow-md p-3 bg-gray-100 rounded-xl lg:w-[400px] ${hoverScale105}`}>
                            <h1 className=" text-xl font-medium pb-2">Lodz University of Technology</h1>
                            <h2 className=" text-lg font-semibold py-1"> Computer Science</h2>
                            <h3 className="font-light py-1">10/2018-10/2022</h3>
                            <h4>
                                Specialization: <span className="font-medium py-1">Database Engineering</span>
                            </h4>
                            <h1 className="text-center  font-thin text-gray-500">Lodz, Poland</h1>
                        </div>
                        <div className={`shadow-md p-3 bg-gray-100 rounded-xl lg:w-[400px] ${hoverScale105}`}>
                            <h1 className=" text-xl font-medium pb-2">Instituto Superior Miguel Torga, Portugal</h1>
                            <h2 className=" text-lg font-semibold py-1"> Computer Science</h2>
                            <h3 className="font-light py-1">09/2021-02/2022</h3>
                            <h4>
                                <span className="font-medium py-1">Erasmus mobility</span>
                            </h4>
                            <h1 className="text-center  font-thin text-gray-500">Coimbra, Portugal</h1>
                        </div>
                    </div>
                </section>
            </main>
        </div>
    );
}
